FROM node:22-alpine AS angular-build
WORKDIR /usr/src/app
ENV NODE_OPTIONS="--max-old-space-size=4096"
COPY package.json package-lock.json ./
RUN npm i --legacy-peer-deps
COPY . .
RUN npx nx build frontend --verbose

FROM nginx:alpine
LABEL author="Preston Lamb"
COPY --from=angular-build /usr/src/app/dist/apps/frontend/browser /usr/share/nginx/html
COPY nginx.conf /etc/nginx/nginx.conf
EXPOSE 8100
CMD [ "nginx", "-g", "daemon off;" ]
